#!/usr/bin/env python
"""
A template file to simulate a specific system of Ordinary Differential Equations (ODEs).

... or an autogenerated script from the *crnsimulator* Python package.

Note: If this file is executable, it is *autogenerated*.
    This means it contains a system of hardcoded ODEs together with some
    default parameters. While it may be tempting to tweak some functions,
    beware that this file may be overwritten by the next execution of the
    `crnsimulator` executable.  Edits should be done at the source file:
    "crnsimulator.odelib_template.py" or you can provide an alternative
    template file. Use the option --output to avoid overwriting this file.

Usage: 
    python ReactionSimulator2.py --help
"""

import logging
logger = logging.getLogger(__name__)

import argparse
import numpy as np
from scipy.integrate import odeint

class ODETemplateError(Exception):
    pass

rates = {
    
}

def odesystem(p0, t0, r):
    A1_1,A2_1,A1_2,A2_2,A1_3,A2_3,A1_4,A2_4,A1_5,A2_5,B1_1,B2_1,B1_2,B2_2,B1_3,B2_3,B1_4,B2_4,B1_5,B2_5,E1_1,E2_1,E1_2,E2_2,E1_3,E2_3,E1_4,E2_4,E1_5,E2_5,G1_1,G2_1,G1_2,G2_2,G1_3,G2_3,G1_4,G2_4,G1_5,G2_5,T01,T02,T11,T12,T21,T22,T1_1,T1_2,T2_1,T2_2,Xi11_1,Xi12_1,Xi21_1,Xi22_1,Xi11_2,Xi12_2,Xi21_2,Xi22_2,Xi11_3,Xi12_3,Xi21_3,Xi22_3,Xi11_4,Xi12_4,Xi21_4,Xi22_4=p0
    if not r : r = rates


    dA1_1dt = -A1_1*E1_1*T02*T2_1 - A1_1*E2_1*T02*T2_2 + A2_1*E1_1*T01*T1_1 + A2_1*E2_1*T01*T1_2
    dA1_2dt = -A1_1*A1_2*E1_2*T12*T2_1 - A1_1*A1_2*E2_2*T12*T2_2 + A1_1*A2_2*E1_2*T11*T1_1 + A1_1*A2_2*E2_2*T11*T1_2 - A1_2*A2_1*E1_2*T22*T2_1 - A1_2*A2_1*E2_2*T22*T2_2 + A2_1*A2_2*E1_2*T1_1*T21 + A2_1*A2_2*E2_2*T1_2*T21
    dA1_3dt = -A1_2*A1_3*E1_3*T12*T2_1 - A1_2*A1_3*E2_3*T12*T2_2 + A1_2*A2_3*E1_3*T11*T1_1 + A1_2*A2_3*E2_3*T11*T1_2 - A1_3*A2_2*E1_3*T22*T2_1 - A1_3*A2_2*E2_3*T22*T2_2 + A2_2*A2_3*E1_3*T1_1*T21 + A2_2*A2_3*E2_3*T1_2*T21
    dA1_4dt = -A1_3*A1_4*E1_4*T12*T2_1 - A1_3*A1_4*E2_4*T12*T2_2 + A1_3*A2_4*E1_4*T11*T1_1 + A1_3*A2_4*E2_4*T11*T1_2 - A1_4*A2_3*E1_4*T22*T2_1 - A1_4*A2_3*E2_4*T22*T2_2 + A2_3*A2_4*E1_4*T1_1*T21 + A2_3*A2_4*E2_4*T1_2*T21
    dA1_5dt = -A1_4*A1_5*E1_5*T12*T2_1 - A1_4*A1_5*E2_5*T12*T2_2 + A1_4*A2_5*E1_5*T11*T1_1 + A1_4*A2_5*E2_5*T11*T1_2 - A1_5*A2_4*E1_5*T22*T2_1 - A1_5*A2_4*E2_5*T22*T2_2 + A2_4*A2_5*E1_5*T1_1*T21 + A2_4*A2_5*E2_5*T1_2*T21
    dA2_1dt = A1_1*E1_1*T02*T2_1 + A1_1*E2_1*T02*T2_2 - A2_1*E1_1*T01*T1_1 - A2_1*E2_1*T01*T1_2
    dA2_2dt = A1_1*A1_2*E1_2*T12*T2_1 + A1_1*A1_2*E2_2*T12*T2_2 - A1_1*A2_2*E1_2*T11*T1_1 - A1_1*A2_2*E2_2*T11*T1_2 + A1_2*A2_1*E1_2*T22*T2_1 + A1_2*A2_1*E2_2*T22*T2_2 - A2_1*A2_2*E1_2*T1_1*T21 - A2_1*A2_2*E2_2*T1_2*T21
    dA2_3dt = A1_2*A1_3*E1_3*T12*T2_1 + A1_2*A1_3*E2_3*T12*T2_2 - A1_2*A2_3*E1_3*T11*T1_1 - A1_2*A2_3*E2_3*T11*T1_2 + A1_3*A2_2*E1_3*T22*T2_1 + A1_3*A2_2*E2_3*T22*T2_2 - A2_2*A2_3*E1_3*T1_1*T21 - A2_2*A2_3*E2_3*T1_2*T21
    dA2_4dt = A1_3*A1_4*E1_4*T12*T2_1 + A1_3*A1_4*E2_4*T12*T2_2 - A1_3*A2_4*E1_4*T11*T1_1 - A1_3*A2_4*E2_4*T11*T1_2 + A1_4*A2_3*E1_4*T22*T2_1 + A1_4*A2_3*E2_4*T22*T2_2 - A2_3*A2_4*E1_4*T1_1*T21 - A2_3*A2_4*E2_4*T1_2*T21
    dA2_5dt = A1_4*A1_5*E1_5*T12*T2_1 + A1_4*A1_5*E2_5*T12*T2_2 - A1_4*A2_5*E1_5*T11*T1_1 - A1_4*A2_5*E2_5*T11*T1_2 + A1_5*A2_4*E1_5*T22*T2_1 + A1_5*A2_4*E2_5*T22*T2_2 - A2_4*A2_5*E1_5*T1_1*T21 - A2_4*A2_5*E2_5*T1_2*T21
    dB1_1dt = -B1_1*B1_2*E1_2*T1_1*T21 - B1_1*B1_2*E2_2*T1_2*T21 - B1_1*B2_2*E1_2*T22*T2_1 - B1_1*B2_2*E2_2*T22*T2_2 + B1_2*B2_1*E1_2*T11*T1_1 + B1_2*B2_1*E2_2*T11*T1_2 + B2_1*B2_2*E1_2*T12*T2_1 + B2_1*B2_2*E2_2*T12*T2_2
    dB1_2dt = -B1_2*B1_3*E1_3*T1_1*T21 - B1_2*B1_3*E2_3*T1_2*T21 - B1_2*B2_3*E1_3*T22*T2_1 - B1_2*B2_3*E2_3*T22*T2_2 + B1_3*B2_2*E1_3*T11*T1_1 + B1_3*B2_2*E2_3*T11*T1_2 + B2_2*B2_3*E1_3*T12*T2_1 + B2_2*B2_3*E2_3*T12*T2_2
    dB1_3dt = -B1_3*B1_4*E1_4*T1_1*T21 - B1_3*B1_4*E2_4*T1_2*T21 - B1_3*B2_4*E1_4*T22*T2_1 - B1_3*B2_4*E2_4*T22*T2_2 + B1_4*B2_3*E1_4*T11*T1_1 + B1_4*B2_3*E2_4*T11*T1_2 + B2_3*B2_4*E1_4*T12*T2_1 + B2_3*B2_4*E2_4*T12*T2_2
    dB1_4dt = -B1_4*B1_5*E1_5*T1_1*T21 - B1_4*B1_5*E2_5*T1_2*T21 - B1_4*B2_5*E1_5*T22*T2_1 - B1_4*B2_5*E2_5*T22*T2_2 + B1_5*B2_4*E1_5*T11*T1_1 + B1_5*B2_4*E2_5*T11*T1_2 + B2_4*B2_5*E1_5*T12*T2_1 + B2_4*B2_5*E2_5*T12*T2_2
    dB1_5dt = 0
    dB2_1dt = B1_1*B1_2*E1_2*T1_1*T21 + B1_1*B1_2*E2_2*T1_2*T21 + B1_1*B2_2*E1_2*T22*T2_1 + B1_1*B2_2*E2_2*T22*T2_2 - B1_2*B2_1*E1_2*T11*T1_1 - B1_2*B2_1*E2_2*T11*T1_2 - B2_1*B2_2*E1_2*T12*T2_1 - B2_1*B2_2*E2_2*T12*T2_2
    dB2_2dt = B1_2*B1_3*E1_3*T1_1*T21 + B1_2*B1_3*E2_3*T1_2*T21 + B1_2*B2_3*E1_3*T22*T2_1 + B1_2*B2_3*E2_3*T22*T2_2 - B1_3*B2_2*E1_3*T11*T1_1 - B1_3*B2_2*E2_3*T11*T1_2 - B2_2*B2_3*E1_3*T12*T2_1 - B2_2*B2_3*E2_3*T12*T2_2
    dB2_3dt = B1_3*B1_4*E1_4*T1_1*T21 + B1_3*B1_4*E2_4*T1_2*T21 + B1_3*B2_4*E1_4*T22*T2_1 + B1_3*B2_4*E2_4*T22*T2_2 - B1_4*B2_3*E1_4*T11*T1_1 - B1_4*B2_3*E2_4*T11*T1_2 - B2_3*B2_4*E1_4*T12*T2_1 - B2_3*B2_4*E2_4*T12*T2_2
    dB2_4dt = B1_4*B1_5*E1_5*T1_1*T21 + B1_4*B1_5*E2_5*T1_2*T21 + B1_4*B2_5*E1_5*T22*T2_1 + B1_4*B2_5*E2_5*T22*T2_2 - B1_5*B2_4*E1_5*T11*T1_1 - B1_5*B2_4*E2_5*T11*T1_2 - B2_4*B2_5*E1_5*T12*T2_1 - B2_4*B2_5*E2_5*T12*T2_2
    dB2_5dt = 0
    dE1_1dt = 0
    dE1_2dt = 0
    dE1_3dt = 0
    dE1_4dt = 0
    dE1_5dt = 0
    dE2_1dt = 0
    dE2_2dt = 0
    dE2_3dt = 0
    dE2_4dt = 0
    dE2_5dt = 0
    dG1_1dt = A1_1*B1_1*G2_1 - A2_1*B2_1*G1_1
    dG1_2dt = A1_2*B1_2*G2_2 - A2_2*B2_2*G1_2
    dG1_3dt = A1_3*B1_3*G2_3 - A2_3*B2_3*G1_3
    dG1_4dt = A1_4*B1_4*G2_4 - A2_4*B2_4*G1_4
    dG1_5dt = A1_5*B1_5*G2_5 - A2_5*B2_5*G1_5
    dG2_1dt = -A1_1*B1_1*G2_1 + A2_1*B2_1*G1_1
    dG2_2dt = -A1_2*B1_2*G2_2 + A2_2*B2_2*G1_2
    dG2_3dt = -A1_3*B1_3*G2_3 + A2_3*B2_3*G1_3
    dG2_4dt = -A1_4*B1_4*G2_4 + A2_4*B2_4*G1_4
    dG2_5dt = -A1_5*B1_5*G2_5 + A2_5*B2_5*G1_5
    dT01dt = 0
    dT02dt = 0
    dT11dt = -T11*Xi12_1 - T11*Xi12_2 - T11*Xi12_3 - T11*Xi12_4 + T12*Xi11_1 + T12*Xi11_2 + T12*Xi11_3 + T12*Xi11_4
    dT12dt = T11*Xi12_1 + T11*Xi12_2 + T11*Xi12_3 + T11*Xi12_4 - T12*Xi11_1 - T12*Xi11_2 - T12*Xi11_3 - T12*Xi11_4
    dT1_1dt = E1_1*G1_1 + E1_2*G1_2 + E1_3*G1_3 + E1_4*G1_4 + E1_5*G1_5 - G1_1*T1_1 - G1_2*T1_1 - G1_3*T1_1 - G1_4*T1_1 - G1_5*T1_1
    dT1_2dt = E2_1*G1_1 + E2_2*G1_2 + E2_3*G1_3 + E2_4*G1_4 + E2_5*G1_5 - G1_1*T1_2 - G1_2*T1_2 - G1_3*T1_2 - G1_4*T1_2 - G1_5*T1_2
    dT21dt = -T21*Xi22_1 - T21*Xi22_2 - T21*Xi22_3 - T21*Xi22_4 + T22*Xi21_1 + T22*Xi21_2 + T22*Xi21_3 + T22*Xi21_4
    dT22dt = T21*Xi22_1 + T21*Xi22_2 + T21*Xi22_3 + T21*Xi22_4 - T22*Xi21_1 - T22*Xi21_2 - T22*Xi21_3 - T22*Xi21_4
    dT2_1dt = E1_1*G2_1 + E1_2*G2_2 + E1_3*G2_3 + E1_4*G2_4 + E1_5*G2_5 - G2_1*T2_1 - G2_2*T2_1 - G2_3*T2_1 - G2_4*T2_1 - G2_5*T2_1
    dT2_2dt = E2_1*G2_1 + E2_2*G2_2 + E2_3*G2_3 + E2_4*G2_4 + E2_5*G2_5 - G2_1*T2_2 - G2_2*T2_2 - G2_3*T2_2 - G2_4*T2_2 - G2_5*T2_2
    dXi11_1dt = A1_1*B1_2*E1_2*T11*T1_1*Xi22_1 + A1_1*B1_2*E2_2*T11*T1_2*Xi22_1 - A2_1*B2_2*E1_2*T22*T2_1*Xi11_1 - A2_1*B2_2*E2_2*T22*T2_2*Xi11_1
    dXi11_2dt = A1_2*B1_3*E1_3*T11*T1_1*Xi22_2 + A1_2*B1_3*E2_3*T11*T1_2*Xi22_2 - A2_2*B2_3*E1_3*T22*T2_1*Xi11_2 - A2_2*B2_3*E2_3*T22*T2_2*Xi11_2
    dXi11_3dt = A1_3*B1_4*E1_4*T11*T1_1*Xi22_3 + A1_3*B1_4*E2_4*T11*T1_2*Xi22_3 - A2_3*B2_4*E1_4*T22*T2_1*Xi11_3 - A2_3*B2_4*E2_4*T22*T2_2*Xi11_3
    dXi11_4dt = A1_4*B1_5*E1_5*T11*T1_1*Xi22_4 + A1_4*B1_5*E2_5*T11*T1_2*Xi22_4 - A2_4*B2_5*E1_5*T22*T2_1*Xi11_4 - A2_4*B2_5*E2_5*T22*T2_2*Xi11_4
    dXi12_1dt = A1_1*B2_2*E1_2*T12*T2_1*Xi22_1 + A1_1*B2_2*E2_2*T12*T2_2*Xi22_1 - A2_1*B2_2*E1_2*T22*T2_1*Xi12_1 - A2_1*B2_2*E2_2*T22*T2_2*Xi12_1
    dXi12_2dt = A1_2*B2_3*E1_3*T12*T2_1*Xi22_2 + A1_2*B2_3*E2_3*T12*T2_2*Xi22_2 - A2_2*B2_3*E1_3*T22*T2_1*Xi12_2 - A2_2*B2_3*E2_3*T22*T2_2*Xi12_2
    dXi12_3dt = A1_3*B2_4*E1_4*T12*T2_1*Xi22_3 + A1_3*B2_4*E2_4*T12*T2_2*Xi22_3 - A2_3*B2_4*E1_4*T22*T2_1*Xi12_3 - A2_3*B2_4*E2_4*T22*T2_2*Xi12_3
    dXi12_4dt = A1_4*B2_5*E1_5*T12*T2_1*Xi22_4 + A1_4*B2_5*E2_5*T12*T2_2*Xi22_4 - A2_4*B2_5*E1_5*T22*T2_1*Xi12_4 - A2_4*B2_5*E2_5*T22*T2_2*Xi12_4
    dXi21_1dt = A2_1*B1_2*E1_2*T1_1*T21*Xi22_1 + A2_1*B1_2*E2_2*T1_2*T21*Xi22_1 - A2_1*B2_2*E1_2*T22*T2_1*Xi21_1 - A2_1*B2_2*E2_2*T22*T2_2*Xi21_1
    dXi21_2dt = A2_2*B1_3*E1_3*T1_1*T21*Xi22_2 + A2_2*B1_3*E2_3*T1_2*T21*Xi22_2 - A2_2*B2_3*E1_3*T22*T2_1*Xi21_2 - A2_2*B2_3*E2_3*T22*T2_2*Xi21_2
    dXi21_3dt = A2_3*B1_4*E1_4*T1_1*T21*Xi22_3 + A2_3*B1_4*E2_4*T1_2*T21*Xi22_3 - A2_3*B2_4*E1_4*T22*T2_1*Xi21_3 - A2_3*B2_4*E2_4*T22*T2_2*Xi21_3
    dXi21_4dt = A2_4*B1_5*E1_5*T1_1*T21*Xi22_4 + A2_4*B1_5*E2_5*T1_2*T21*Xi22_4 - A2_4*B2_5*E1_5*T22*T2_1*Xi21_4 - A2_4*B2_5*E2_5*T22*T2_2*Xi21_4
    dXi22_1dt = -A1_1*B1_2*E1_2*T11*T1_1*Xi22_1 - A1_1*B1_2*E2_2*T11*T1_2*Xi22_1 - A1_1*B2_2*E1_2*T12*T2_1*Xi22_1 - A1_1*B2_2*E2_2*T12*T2_2*Xi22_1 - A2_1*B1_2*E1_2*T1_1*T21*Xi22_1 - A2_1*B1_2*E2_2*T1_2*T21*Xi22_1 + A2_1*B2_2*E1_2*T22*T2_1*Xi11_1 + A2_1*B2_2*E1_2*T22*T2_1*Xi12_1 + A2_1*B2_2*E1_2*T22*T2_1*Xi21_1 + A2_1*B2_2*E2_2*T22*T2_2*Xi11_1 + A2_1*B2_2*E2_2*T22*T2_2*Xi12_1 + A2_1*B2_2*E2_2*T22*T2_2*Xi21_1
    dXi22_2dt = -A1_2*B1_3*E1_3*T11*T1_1*Xi22_2 - A1_2*B1_3*E2_3*T11*T1_2*Xi22_2 - A1_2*B2_3*E1_3*T12*T2_1*Xi22_2 - A1_2*B2_3*E2_3*T12*T2_2*Xi22_2 - A2_2*B1_3*E1_3*T1_1*T21*Xi22_2 - A2_2*B1_3*E2_3*T1_2*T21*Xi22_2 + A2_2*B2_3*E1_3*T22*T2_1*Xi11_2 + A2_2*B2_3*E1_3*T22*T2_1*Xi12_2 + A2_2*B2_3*E1_3*T22*T2_1*Xi21_2 + A2_2*B2_3*E2_3*T22*T2_2*Xi11_2 + A2_2*B2_3*E2_3*T22*T2_2*Xi12_2 + A2_2*B2_3*E2_3*T22*T2_2*Xi21_2
    dXi22_3dt = -A1_3*B1_4*E1_4*T11*T1_1*Xi22_3 - A1_3*B1_4*E2_4*T11*T1_2*Xi22_3 - A1_3*B2_4*E1_4*T12*T2_1*Xi22_3 - A1_3*B2_4*E2_4*T12*T2_2*Xi22_3 - A2_3*B1_4*E1_4*T1_1*T21*Xi22_3 - A2_3*B1_4*E2_4*T1_2*T21*Xi22_3 + A2_3*B2_4*E1_4*T22*T2_1*Xi11_3 + A2_3*B2_4*E1_4*T22*T2_1*Xi12_3 + A2_3*B2_4*E1_4*T22*T2_1*Xi21_3 + A2_3*B2_4*E2_4*T22*T2_2*Xi11_3 + A2_3*B2_4*E2_4*T22*T2_2*Xi12_3 + A2_3*B2_4*E2_4*T22*T2_2*Xi21_3
    dXi22_4dt = -A1_4*B1_5*E1_5*T11*T1_1*Xi22_4 - A1_4*B1_5*E2_5*T11*T1_2*Xi22_4 - A1_4*B2_5*E1_5*T12*T2_1*Xi22_4 - A1_4*B2_5*E2_5*T12*T2_2*Xi22_4 - A2_4*B1_5*E1_5*T1_1*T21*Xi22_4 - A2_4*B1_5*E2_5*T1_2*T21*Xi22_4 + A2_4*B2_5*E1_5*T22*T2_1*Xi11_4 + A2_4*B2_5*E1_5*T22*T2_1*Xi12_4 + A2_4*B2_5*E1_5*T22*T2_1*Xi21_4 + A2_4*B2_5*E2_5*T22*T2_2*Xi11_4 + A2_4*B2_5*E2_5*T22*T2_2*Xi12_4 + A2_4*B2_5*E2_5*T22*T2_2*Xi21_4
    return np.array([dA1_1dt,dA2_1dt,dA1_2dt,dA2_2dt,dA1_3dt,dA2_3dt,dA1_4dt,dA2_4dt,dA1_5dt,dA2_5dt,dB1_1dt,dB2_1dt,dB1_2dt,dB2_2dt,dB1_3dt,dB2_3dt,dB1_4dt,dB2_4dt,dB1_5dt,dB2_5dt,dE1_1dt,dE2_1dt,dE1_2dt,dE2_2dt,dE1_3dt,dE2_3dt,dE1_4dt,dE2_4dt,dE1_5dt,dE2_5dt,dG1_1dt,dG2_1dt,dG1_2dt,dG2_2dt,dG1_3dt,dG2_3dt,dG1_4dt,dG2_4dt,dG1_5dt,dG2_5dt,dT01dt,dT02dt,dT11dt,dT12dt,dT21dt,dT22dt,dT1_1dt,dT1_2dt,dT2_1dt,dT2_2dt,dXi11_1dt,dXi12_1dt,dXi21_1dt,dXi22_1dt,dXi11_2dt,dXi12_2dt,dXi21_2dt,dXi22_2dt,dXi11_3dt,dXi12_3dt,dXi21_3dt,dXi22_3dt,dXi11_4dt,dXi12_4dt,dXi21_4dt,dXi22_4dt])

#<&>JACOBIAN<&>#


def add_integrator_args(parser):
    """ODE integration aruments."""
    solver = parser.add_argument_group('odeint parameters')
    plotter = parser.add_argument_group('plotting parameters')

    # required: simulation time and output settings
    solver.add_argument("--t0", type=float, default=0, metavar='<flt>',
            help="First time point of the time-course.")
    solver.add_argument("--t8", type=float, default=100, metavar='<flt>',
            help="End point of simulation time.")
    plotter.add_argument("--t-lin", type=int, default=500, metavar='<int>',
            help="Returns --t-lin evenly spaced numbers on a linear scale from --t0 to --t8.")
    plotter.add_argument("--t-log", type=int, default=None, metavar='<int>',
            help="Returns --t-log evenly spaced numbers on a logarithmic scale from --t0 to --t8.")

    # required: initial concentration vector
    solver.add_argument("--p0", nargs='+', metavar='<int/str>=<flt>',
            help="""Vector of initial species concentrations. 
            E.g. \"--p0 1=0.5 3=0.7\" stands for 1st species at a concentration of 0.5 
            and 3rd species at a concentration of 0.7. You may chose to address species
            directly by name, e.g.: --p0 C=0.5.""")
    # advanced: scipy.integrate.odeint parameters
    solver.add_argument("-a", "--atol", type=float, default=None, metavar='<flt>',
            help="Specify absolute tolerance for the solver.")
    solver.add_argument("-r", "--rtol", type=float, default=None, metavar='<flt>',
            help="Specify relative tolerance for the solver.")
    solver.add_argument("--mxstep", type=int, default=0, metavar='<int>',
            help="Maximum number of steps allowed for each integration point in t.")

    # optional: choose output formats
    plotter.add_argument("--list-labels", action='store_true',
            help="Print all species and exit.")
    plotter.add_argument("--labels", nargs='+', default=[], metavar='<str>+',
            help="""Specify the (order of) species which should appear in the pyplot legend, 
            as well as the order of species for nxy output format.""")
    plotter.add_argument("--labels-strict", action='store_true',
            help="""When using pyplot, only plot tracjectories corresponding to labels,
            when using nxy, only print the trajectories corresponding to labels.""")
 
    plotter.add_argument("--nxy", action='store_true',
            help="Print time course to STDOUT in nxy format.")
    plotter.add_argument("--header", action='store_true',
            help="Print header for trajectories.")

    plotter.add_argument("--pyplot", default='', metavar='<str>',
            help="Specify a filename to plot the ODE simulation.")
    plotter.add_argument("--pyplot-xlim", nargs=2, type=float, default=None, metavar='<flt>',
            help="Specify the limits of the x-axis.")
    plotter.add_argument("--pyplot-ylim", nargs=2, type=float, default=None, metavar='<flt>',
            help="Specify the limits of the y-axis.")
    plotter.add_argument("--pyplot-labels", nargs='+', default=[], metavar='<str>+',
            help=argparse.SUPPRESS)
    return

def flint(inp):
    return int(float(inp)) if float(inp) == int(float(inp)) else float(inp)

def set_logger(verbose, logfile):
    # ~~~~~~~~~~~~~
    # Logging Setup 
    # ~~~~~~~~~~~~~
    logger.setLevel(logging.DEBUG)
    handler = logging.FileHandler(logfile) if logfile else logging.StreamHandler()
    if verbose == 0:
        handler.setLevel(logging.WARNING)
    elif verbose == 1:
        handler.setLevel(logging.INFO)
    elif verbose == 2:
        handler.setLevel(logging.DEBUG)
    elif verbose >= 3:
        handler.setLevel(logging.NOTSET)
    formatter = logging.Formatter('%(levelname)s - %(message)s')
    handler.setFormatter(formatter)
    logger.addHandler(handler)


def integrate(args, setlogger = False):
    """Main interface to solve the ODE-system.

    Args:
      args (:obj:`argparse.ArgumentParser()`): An argparse object containing all of
        the arguments of :obj:`crnsimulator.add_integrator_args()`.

    Prints:
      - plot files
      - time-course

    Returns:
      Nothing
    """
    if setlogger:
        set_logger(args.verbose, args.logfile)

    if args.pyplot_labels:
        logger.warning('Deprecated argument: --pyplot_labels.')

    svars=['A1_1', 'A2_1', 'A1_2', 'A2_2', 'A1_3', 'A2_3', 'A1_4', 'A2_4', 'A1_5', 'A2_5', 'B1_1', 'B2_1', 'B1_2', 'B2_2', 'B1_3', 'B2_3', 'B1_4', 'B2_4', 'B1_5', 'B2_5', 'E1_1', 'E2_1', 'E1_2', 'E2_2', 'E1_3', 'E2_3', 'E1_4', 'E2_4', 'E1_5', 'E2_5', 'G1_1', 'G2_1', 'G1_2', 'G2_2', 'G1_3', 'G2_3', 'G1_4', 'G2_4', 'G1_5', 'G2_5', 'T01', 'T02', 'T11', 'T12', 'T21', 'T22', 'T1_1', 'T1_2', 'T2_1', 'T2_2', 'Xi11_1', 'Xi12_1', 'Xi21_1', 'Xi22_1', 'Xi11_2', 'Xi12_2', 'Xi21_2', 'Xi22_2', 'Xi11_3', 'Xi12_3', 'Xi21_3', 'Xi22_3', 'Xi11_4', 'Xi12_4', 'Xi21_4', 'Xi22_4']

    p0 =[0.6, 0.4000000000000001, 0.58, 0.42000000000000004, 0.574, 0.426, 0.5721999999999999, 0.42779999999999996, 0.57166, 0.42834, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.49999999999999994, 0.5, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.6, 0.4000000000000001, 0.58, 0.4200000000000001, 0.5740000000000001, 0.42600000000000005, 0.5721999999999999, 0.4278, 0.57166, 0.42834, 0.6, 0.4, 0.7, 0.3, 0.4, 0.6, 0.6, 0.4, 0.6, 0.4, 0.41999999999999993, 0.17999999999999997, 0.16000000000000003, 0.24000000000000002, 0.40599999999999997, 0.17400000000000002, 0.168, 0.252, 0.40179999999999993, 0.17220000000000002, 0.17040000000000002, 0.2556, 0.40053999999999995, 0.17166, 0.17112000000000002, 0.25668]
    
    const = None
    #<&>CONSTANT_SPECIES_INFO<&>#
    if args.p0:
        for term in args.p0:
            p, o = term.split('=')
            try:
                pi = svars.index(p)
            except ValueError as e:
                pi = int(p) - 1
            finally:
                p0[pi] = flint(o)
    else:
        msg = 'Specify a vector of initial concentrations: ' + \
                'e.g. --p0 1=0.1 2=0.005 3=1e-6 (see --help)'
        if sum(p0) == 0:
            logger.warning(msg)
            args.list_labels = True
        else:
            logger.info(msg)

    if args.list_labels:
        print('List of variables and initial concentrations:')
        for e, v in enumerate(svars, 1):
            if args.labels_strict and e > len(args.labels):
                break
            print(f'{e} {v} {p0[e-1]} {"constant" if const and const[e-1] else ""}')
        raise SystemExit('Initial concentrations can be overwritten by --p0 argument')

    if not args.nxy and not args.pyplot:
        logger.warning('Use --pyplot and/or --nxy to plot your results.')

    if not args.t8:
        raise ODETemplateError('Specify a valid end-time for the simulation: --t8 <flt>')

    if args.t_log:
        if args.t0 == 0:
            raise ODETemplateError('--t0 cannot be 0 when using log-scale!')
        time = np.logspace(np.log10(args.t0), np.log10(args.t8), num=args.t_log)
    elif args.t_lin:
        time = np.linspace(args.t0, args.t8, num=args.t_lin)
    else:
        raise ODETemplateError('Please specify either --t-lin or --t-log. (see --help)')

    # It would be nice if it is possible to read alternative rates from a file instead.
    # None triggers the default-rates that are hard-coded in the (this) library file.
    rates = None

    logger.info(f'Initial concentrations: {list(zip(svars, p0))}')
    # TODO: logging should report more info on parameters.

    ny = odeint(odesystem,
        np.array(p0), time, (rates, ), #<&>JCALL<&>#,
        atol=args.atol, rtol=args.rtol, mxstep=args.mxstep).T

    # Output
    if args.nxy and args.labels_strict:
        end = len(args.labels)
        if args.header:
            print(' '.join(['{:15s}'.format(x) for x in ['time'] + svars[:end]]))
        for i in zip(time, *ny[:end]):
            print(' '.join(map("{:.9e}".format, i)))
    elif args.nxy:
        if args.header:
            print(' '.join(['{:15s}'.format(x) for x in ['time'] + svars]))
        for i in zip(time, *ny):
            print(' '.join(map("{:.9e}".format, i)))

    if args.pyplot:
        from crnsimulator.plotting import ode_plotter
        plotfile = ode_plotter(args.pyplot, time, ny, svars,
                               log=True if args.t_log else False,
                               labels=set(args.labels),
                               xlim = args.pyplot_xlim,
                               ylim = args.pyplot_ylim,
                               labels_strict = args.labels_strict)
        logger.info(f"Plotting successfull. Wrote plot to file: {plotfile}")

    return zip(time, *ny)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument("-v", "--verbose", action='count', default = 0,
        help = "Print logging output. (-vv increases verbosity.)")
    parser.add_argument('--logfile', default = '', action = 'store', metavar = '<str>',
        help = """Redirect logging information to a file.""")
    add_integrator_args(parser)
    args = parser.parse_args()
    integrate(args, setlogger = True)
